server:
  port: 8081

spring:
  application:
    name: packing-iso-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Configuration pour Feign (utilisation temporaire via URL)
response-iso-service:
  url: http://localhost:8082
